
server:
  port: 8761
spring:
  application:
    name: first-cloud-server
  profiles: slave1
eureka:
  client:instance:
    hostname: slave1
    service-url:
      defaultZone: http://localhost:8762/eureka/
---
server:
  port: 8762
spring:
  application:
    name: first-cloud-server
  profiles: slave2
eureka:
  client:instance:
    hostname: slave2
    service-url:
      defaultZone: http://localhost:8761/eureka/